### ISSUE TITLE
Compatibility with @module-federation/enhanced

### ISSUE THREAD

**Issue by sudhakar-selva** [module-federation/external-remotes-plugin#10]
**Issue**
**Update**
Solution: https://github.com/module-federation/core/issues/2125 (via new plugin system - 🤦)

We are trying to move to @module-federation/enhanced. Our current version uses federation plugin exposed by webpack with external-remotes-plugin. However, external-remotes-plugin seems to not be working for @module-federation/enhanced. Is it possible to achieve similar functionality with @module-federation/enhanced, or is there any other recommended approach for migration? 

Thanks!

```js
new ModuleFederationPlugin({
   name: 'host',
   filename: 'host.remoteEntry.js',
   remotes: {
       app: 'app@[appPortalUrl]/app.remoteEntry.js',
        // other remotes...
    }
})
```

**Comment by AdarshJais** [comment]
Did you got the solution for this?

**Comment by sudhakar-selva** [comment]
Yes @AdarshJais - https://github.com/module-federation/core/issues/2125 (via new plugin system)

**Comment by 86XIng** [comment]
Wrote a runtime plugin for that.
https://www.npmjs.com/package/runtime-external-remotes-plugin
